### ISSUE TITLE
bug: unable to download package - 403

### ISSUE THREAD

**Issue by krnbr** [checkly/pulumi-checkly#29]
### Pulumi version

v3.38.0

### Provider version

v1.1.2

### Steps to reproduce

unable to download the plugin

 https://get.pulumi.com/releases/plugins/pulumi-resource-checkly-v1.1.2-windows-amd64.tar.gz
 
 This url gives 403

### What is expected?

Should be downloaded easily

### What is actually happening?

Giving 403

[resource plugin checkly-1.1.0] installing
warning: Error downloading plugin: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-checkly-v1.1.2-windows-amd64.tar.gz

**Comment by krnbr** [comment]
Till then the available option is 

`pulumi plugin install resource -f=<path>\pulumi-resource-checkly-v1.1.2-windows-amd64.tar.gz checkly v1.1.2`

**Comment by AaronFriel** [comment]
Hey @krnbr, we're shipping a fix to Pulumi to address this, tracking the issue here: https://github.com/pulumi/pulumi/issues/10648

**Comment by AaronFriel** [comment]
This should be resolved in 3.39.3, installing the node module or plugin via other means should automatically install it. Please let me know if that doesn't work!

**Comment by Marwennnne** [comment]
@AaronFriel I am having this problem
Pulumi version: 3.58.0

**Comment by ianaya89** [comment]
@Marwennnne, which provider version are you using?

**Comment by Marwennnne** [comment]
@ianaya89 v1.1.2
I tried with v1.1.4 same thing

**Comment by Marwennnne** [comment]
I didn't have this problem in my CI CD until today

**Comment by AaronFriel** [comment]
Are you on the latest version of the Pulumi CLI?
